### ISSUE TITLE
copy and rewrite (edit to point to the new files) m3u playlists

### ISSUE THREAD

**Issue by quantenzitrone** [geigerzaehler/beets-alternatives#116]
I manage the music i listen to in m3u playlist files, so when i create an alternative folder with all my music transcoded to opus so it fits on my phone, i also want my playlists copied.
Right now i have to do that manually.

**Comment by geigerzaehler** [comment]
Hi @quantenzitrone. To get a better idea of your use case I have a couple of questions:

Are you using any of the beets playlist plugins to manage your playlists? Could you share your configuration? Where are the playlists located? Are you using a different file structure for your alternative folder?

I guess the main challenge in designing this feature will be figuring out how it works with playlist plugins and queries. If you have any suggestions feel free to post them.

**Comment by quantenzitrone** [comment]
1. i use the playlist plugin to automatically rewrite the paths in playlists if the directory structure changes.
2. sure: 
<details>
<summary>beets config (without the secrets obviously)</summary>

```yaml
replace: {
    # slashes
    "/": "⧸",
    # dots at the beginning (so files are not hidden)
    '^\.': "․",
    # remove ascii control characters
    '[\x00-\x1f]': "_",
    # spaces at the beginning and and
    '\s+$': "",
    '^\s+': "",
    # dash at the beginning (to not break dumbly programmed commandline tools)
    "^-": "_",
    # russian А to latin A so i can shell complete Aмура
    "А": "A",
  }
path_sep_replace: "⧸"
paths:
  default: '%first{$albumartists,1,0,\␀}/$album [$year]/$track - $title'
  singleton: '%first{$artists,1,0,\␀}/Tracks/$title'
  comp: "Compilations/$album [$year]/$track - $title"
  albumtype:single: '%first{$artists,1,0,\␀}/Singles/$title [$year]'

match:
  preferred:
    countries: ["XW", "XE"]
    media: ["Digital Media"]
    original_year: true
  max_rec:
    chroma: high
chroma:
  auto: true

plugins:
  [
    unimported,
    bareasc,
    fish,
    badfiles,
    duplicates,
    albumtypes,
    chroma,
    lyrics,
    embedart,
    fetchart,
    playlist,
    mbsync,
    info,
    advancedrewrite,
    scrub,
    mbcollection,
    replaygain,
    play,
    alternatives,
    convert,
    checkplaylist,
    substitute,
  ]

# additionally remove all characters that dont work on fat32
substitute:
  '["*/:<>?\|+,\.;=!@]|\]|\[' : '_'

alternatives:
  opus:
    directory: /data/music/opusmusic
    formats: opus
    paths:
      default: '%if{$mb_trackid,$mb_trackid,no-mbid/%lower{%left{$acoustid_fingerprint,50}}}'
    query: "
      playlist:'Calm Vocals',
      playlist:'Cyberphonk',
      playlist:'Heavy Trap',
      playlist:'Metal',
      playlist:'Novah',
      playlist:'Trip In Multiverse',
      playlist:'Rap',
      playlist:'Sad Rap'
      "
    removable: false

convert:
  formats:
    opus: "/data/music/__bin/convert-to-opus.fish $source $dest"

play:
  command: mpv

replaygain:
  backend: ffmpeg
  overwrite: true
  # YouTube, Spotify, Tidal and Amazon normalize to -14 LUFS -> 93 db
  targetlevel: 93
  r128_targetlevel: 93

musicbrainz:
  genres: true

playlist:
  auto: true
  playlist_dir: /data/music/hqmusic

unimported:
  ignore_extensions: [
      # ignore lyrics files
      lrc,
      txt,
      # ignore playlists
      m3u,
      # ignore additional metadata files
      rss,
      norss,
      # ignore images
      jpg,
      jpeg,
      png,
    ]

badfiles:
  check_on_import: true
  commands:
    opus: opusinfo
    ogg: ogginfo

lyrics:
  synced: true

fetchart:
  sources: 
    - coverart: release
  high_resolution: true

embedart:
  remove_art_file: true

advancedrewrite:
  - match: mb_albumid:"4015a325-5dee-4562-870e-f63c648931b9"
    replacements:
      album: "Happier Than Ever (edit)"

```
</details>

3. The playlists are located in the root music directory. 
4. My alternate folder uses a different file structure, because android is dumb and doesn't permit all the special characters that are allowed on ext4 or similarly modern linux file systems. The paths also change because i convert the music to opus.
