### ISSUE TITLE
[question] conversions and copies always run for recently added items

### ISSUE THREAD

**Issue by mcrosson** [geigerzaehler/beets-alternatives#121]
I've been using the plugin for a long time and recently it's started always converting and copying items. However, it's only for my most recent beets imports, not my full library.

I've checked the output folders and they have the files I'd expect to see, the timestamp on the converted/copied files is after the source files and I've not applied any changes to my beets library or source files between runs. I did notice my library is now over 100k tracks but I'm not sure how such a thing could impact this plugin.

I'm wondering if there are any other checks I can perform to try to figure out why the plugin is running conversions/copies for all of the more recently imported items to my beets library.

---

Filesystem: `docker volume mount backed by zfs on arch linux`

Plugin Version: `0.13.1`

Beets Version: `2.2.0`

Python Version: `3.12.3`

Config:

``` yaml
##########
# /opt/music/beets/library.yaml
statefile: /opt/music/beets/library.state.pickle
library: /opt/music/beets/library.db
directory: /opt/music/library

plugins: xtractor replaygain web types describe info chroma summarize missing duplicates inline scrub ftintitle mbsync lastgenre embedart fetchart edit unimported badfiles convert alternatives

threaded: yes
ignore_hidden: true
asciify_paths: yes
original_date: yes

ui:
  color: yes

web:
  host: 0.0.0.0

import:
  autotag: yes
  timid: yes
  write: no
  copy: no
  move: no
  log: /opt/tmp/beetslog.txt

paths:
  default: $albumartist/$album%aunique{}/%if{$multidisc,$disc - }$track - $title
  singleton: $albumartist/[non-album tracks]/$title
  comp: Various Artists/$album%aunique{}/%if{$multidisc,$disc - }/$track - $title
  albumtype:soundtrack: Soundtrack/$album%aunique{}/%if{$multidisc,$disc - }/$track - $title

item_fields:
  multidisc: 1 if disctotal > 1 else 0

types:
  kmn_import: int
  kmn_sevend: bool

unimported:
  ignore_extensions: jpg png

badfiles:
  check_on_import: no
  commands:
    flac: python3 -c 'import sys ; import os.path ; val = 0 if os.path.isfile(sys.argv[1]) else 1; sys.exit(val);'
    m4a: python3 -c 'import sys ; import os.path ; val = 0 if os.path.isfile(sys.argv[1]) else 1; sys.exit(val);'
    mp3: python3 -c 'import sys ; import os.path ; val = 0 if os.path.isfile(sys.argv[1]) else 1; sys.exit(val);'
    aac: python3 -c 'import sys ; import os.path ; val = 0 if os.path.isfile(sys.argv[1]) else 1; sys.exit(val);'
    ape: python3 -c 'import sys ; import os.path ; val = 0 if os.path.isfile(sys.argv[1]) else 1; sys.exit(val);'

duplicates:
  format: $albumartist - $album - $track - $path
  full: yes

match:
  preferred:
    countries: [ 'US', 'XW' ]
    media: ['CD', 'Digital Media|File']
    original_year: yes

ftintitle:
  auto: no
  drop: no
  format: "feat. {0}"

embedart:
  auto: no

scrub:
  auto: no

lastgenre:
  count: 1
  prefer_specific: yes
  source: album

fetchart:
  auto: no
  google_key: ""
  lastfm_key: ""
  sources:
    #- filesystem
    - coverart: release releasegroup
    - itunes
    - lastfm
  store_source: no
  min_width: 1000
  max_width: 1500

chroma:
  auto: no

replaygain:
  auto: no
  write: no
  threads: 10
  parallel_on_import: yes
  backend: ffmpeg
  overwrite: no

convert:
  delete_originals: false
  auto: no
  copy_album_art: yes
  embed: yes
  never_convert_lossy_files: yes
  threads: 10
  format: m4a
  formats:
    m4a:
      extension: m4a
      command: ffmpeg -i $source -y -c:v copy -c:a libfdk_aac -vbr 5 $dest
    aac:
      extension: aac
      command: ffmpeg -i $source -y -c:a libfdk_aac -vbr 5 $dest

alternatives:
  airsonic:
    directory: /opt/music/alternatives
    formats: m4a aac mp3
    query: ""
    removable: false

xtractor:
  auto: yes
  dry-run: no
  write: no # flip to yes for prod use
  threads: 10
  force: no
  quiet: no
  keep_output: yes
  keep_profiles: no
  output_path: /opt/music/beets/xtraction_data
  essentia_extractor: /usr/local/bin/essentia_streaming_extractor_music
  extractor_profile:
    highlevel:
      svm_models:
        - /usr/local/share/essentia/svm_models/danceability.history
        - /usr/local/share/essentia/svm_models/gender.history
        - /usr/local/share/essentia/svm_models/genre_rosamerica.history
        - /usr/local/share/essentia/svm_models/mood_acoustic.history
        - /usr/local/share/essentia/svm_models/mood_aggressive.history
        - /usr/local/share/essentia/svm_models/mood_electronic.history
        - /usr/local/share/essentia/svm_models/mood_happy.history
        - /usr/local/share/essentia/svm_models/mood_sad.history
        - /usr/local/share/essentia/svm_models/mood_party.history
        - /usr/local/share/essentia/svm_models/mood_relaxed.history
        - /usr/local/share/essentia/svm_models/voice_instrumental.history
        - /usr/local/share/essentia/svm_models/moods_mirex.history
```
