### ISSUE TITLE
Encoded files in alt are encoded again during `alt update`

### ISSUE THREAD

**Issue by seadowg** [geigerzaehler/beets-alternatives#67]
When running `alt update`, files that have previously been encoded (by earlier `alt update` runs) seem to be re-encoded. For instance, I've already run an `alt update` that included this version of Loveless but every time I run I see this again:

```
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/01 Only Shallow.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/02 Loomer.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/03 Touched.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/04 To Here Knows When.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/05 When You Sleep.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/06 I Only Said.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/07 Come in Alone.flac
convert: Finished encoding /my/beets/library/dir/My Bloody Valentine/Loveless/03 Touched.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/08 Sometimes.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/09 Blown a Wish.flac
convert: Finished encoding /my/beets/library/dir/My Bloody Valentine/Loveless/02 Loomer.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/10 What You Want.flac
convert: Finished encoding /my/beets/library/dir/My Bloody Valentine/Loveless/07 Come in Alone.flac
convert: Encoding /my/beets/library/dir/My Bloody Valentine/Loveless/11 Soon.flac
convert: Finished encoding /my/beets/library/dir/My Bloody Valentine/Loveless/01 Only Shallow.flac
convert: Finished encoding /my/beets/library/dir/My Bloody Valentine/Loveless/05 When You Sleep.flac
convert: Finished encoding /my/beets/library/dir/My Bloody Valentine/Loveless/09 Blown a Wish.flac
```

I have a `alt` setup to convert to lossy formats from my lossless ones for my phone, and it seem to slow down and run through this encode step for every lossless track which means the process gets slower and slower every time I add an album in FLAC. 

My config looks like this:

```
directory: /my/beets/library/dir/
library: /my/beets/library/dir/beet-library.db
plugins: convert alternatives copyartifacts
convert:
  copy_album_art: yes
  never_convert_lossy_files: yes
  formats:
    cd:
      command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 $dest
      extension: flac
    mobile:
      command: ffmpeg -i $source -y -vn -ab 320k -ar 44100 $dest
      extension: mp3
alternatives:
  cloudplayer:
    directory: /my/alt/library/dir
    formats: mobile AAC aac mp3
    query: ""
    removable: true
copyartifacts:
    extensions: .pdf .jpg .png
    print_ignored: yes
```
