### ISSUE TITLE
Every album re-copied on each update

### ISSUE THREAD

**Issue by loafofpiecrust** [geigerzaehler/beets-alternatives#74]
I just started using this plugin, and the first time I ran `beets alt update ipod` after setting things up worked just fine. It took all night, as expected. However, after I added a new album to my library and then ran `beets alt update ipod` again, it first printed `+` lines with the new tracks. Then it appeared to print all of my tracks and it looks like it's also going to take hours. I'm guessing it's re-copying over some files each time, which defeats the purpose of this for me coming from using a simple `rsync` script.
Maybe I made a mistake at some point? Or maybe this is an interaction with the `extrafiles` plugin? Here's my config...

<details>
<summary>config.yaml</summary>

```yaml
directory: /run/media/snead/icepack/music
library: ~/music/beets-library.db
original_date: yes
format_album: $albumartist - [$original_year/$year] $album
format_item: $artist - $album - $disc.$track. $title
sort_album: albumartist+ year+ album+
per_disc_numbering: yes
import:
  autotag: no
  copy: no
  timid: yes
  languages: en
  incremental: yes
  incremental_skip_later: yes
match:
  preferred:
    countries: ['US', 'GB|UK', 'JP']
    media: ['CD', 'DigitalMedia|File', 'Vinyl']
    original_year: yes
musicbrainz:
  extra_tags: [year]
paths:
  albumtype:soundtrack: Soundtracks/[$realyear] $album/%if{$multidisc,Disc %right{$disc,1}/}$track. $title
  comp: %first{$genre}/[$realyear] $album/%if{$multidisc,Disc %right{$disc,1}%if{$grouping,. $grouping}/}$track. $title
  albumtype:single: %the{$albumartist}/Singles/%if{$subartist,[$subartist]}[$realyear] $album/$track. $title
  default: %the{$albumartist}/[$realyear]%if{$subartist,[$subartist]} $album%ifdef{atypes, $atypes}/%if{$multidisc,Disc %right{$disc,1}%if{$grouping,. $grouping}/}$track. $title
item_fields:
  multidisc: 1 if disctotal > 1 else 0
  # MF Doom is something special, with all of his alternate names
  subartist: albumartist_credit if albumartist.lower() != albumartist_credit.lower() else ''
  realyear: original_year if original_year != 0 and original_year < year else year
plugins: the badfiles albumtypes missing rewrite fromfilename inline extrafiles fetchart alternatives convert duplicates
# Automatically resample all hi-fi FLACs down to CD quality on import
convert:
  auto: no
  embed: no
  max_bitrate: 1411
  never_convert_lossy_files: yes
  format: flac
  formats:
    flac: ffmpeg -y -i $source -acodec flac -af aresample=osf=s16:dither_method=triangular:resampler=soxr:out_sample_rate=44100 $dest
fetchart:
  auto: no
  cautious: yes
  cover_names: cover front folder album art
  minwidth: 1000
  enforce_ratio: 2%
  sources: filesystem coverart itunes
  deinterlace: yes
extrafiles:
  patterns:
    images: '*.(jpg|jpeg|png)'
albumtypes:
  types:
    - ep: 'EP'
    - single: 'Single'
    - live: 'Live'
    - compilation: 'Comp'
  ignore_va: compilation
  bracket: '()'
rewrite:
  albumartist DANGERDOOM: MF DOOM
  albumartist Viktor Vaughn: MF DOOM
  albumartist The Jimi Hendrix Experience: Jimi Hendrix
  albumartist Mychael Danna, DeVotchKa: DeVotchKa
  albumartist Adrian Orange: Thanksgiving
  albumartist The Velvet Underground & Nico: The Velvet Underground
  albumartist kidkanevil & Daisuke Tanabe: Daisuke Tanabe
  albumartist David Byrne & St. Vincent: David Byrne
  albumartist filous & Daði Freyr: Daði Freyr
  albumartist J\.U\.F: Gogol Bordello
  albumartist Gorillaz feat.*: Gorillaz
  albumartist Spacemonkeyz vs. Gorillaz: Gorillaz
  albumartist Justin Timberlake & .*: Justin Timberlake
  albumartist The Management: MGMT
  albumartist Urban Thermo Dynamics: Mos Def
  albumartist The Flaming Lips .*: The Flaming Lips
  albumartist Prince and The Revolution: Prince
alternatives:
  ipod:
    directory: /run/media/snead/SHELBY_S IP/music-beets
    query: "onplayer:true"
    removable: true
replace:
  '[\?]$': ''
  '[\\/]': "-"
  '^\.': _
  '<\|': '◀'
  '\|>': '▶'
  '[\x00-\x1f]': _
  ':': ';'
  '"': "'"
  '[<>\?\*\|]': _
  '\.$': ''
  '\s+$': ''
  '^\s+': ''
  '^-': _
  '‐': '-'
duplicates:
  album: yes
  keys: [albumartist, album, year]
```
</details>
