### ISSUE TITLE
beet alt ballons memory, may lead to OOM

### ISSUE THREAD

**Issue by knuurr** [geigerzaehler/beets-alternatives#76]
Using beets-alternavives. I Installed it within docker container. I'm deploying it using docker-compose with hard limits for usage:

```yaml
    deploy:
      resources:
        limits:
          # Adjust as needed
          cpus: '0.5'
          memory: '2048M'
```

I've discovered that running command may lead to OOM condition.
Here's part from inside of container when ran from interactive shell:

```bash
/src # beet alt 

usage: beet alt [-h] {update,list-tracks} ...
beet alt: error: the following arguments are required: {update,list-tracks}
/src # 
/src # beet alt uptade mp3-mirror
usage: beet alt [-h] {update,list-tracks} ...
beet alt: error: argument {update,list-tracks}: invalid choice: 'uptade' (choose from 'update', 'list-tracks')
/src # beet alt update mp3-mirror
     
Killed
/src # 
/src # 
```

Note: "Killed" occured automatically. I didn't do that manually.

This is confirmed from my Grafana output:

![obraz](https://github.com/geigerzaehler/beets-alternatives/assets/135069967/1d3762cc-6c00-44c0-9087-38235f38a4db)
